### ISSUE TITLE
Typo: Moving Liquids Quest says Dirt instead of Dust

### ISSUE THREAD

**Issue by tsGod** [AllTheMods/VolcanoBlock#10]
From the Moving Liquids quest:

```
Using a piece of dirt on a full Barrel of water gives you Clay!
```

Based on JEI, I think this should say dust instead of dirt.

![image](https://github.com/AllTheMods/VolcanoBlock/assets/7573450/486edb93-160f-452b-b97f-10f76072b0fe)

**Comment by oly2o6** [comment]
Fixed in 1.0.1
