### ISSUE TITLE
Bookwrym still flying to the inventory but the inventory has been removed

### ISSUE THREAD

**Issue by EB010-NL** [AllTheMods/VolcanoBlock#101]
Hello i had an inventory places somewhere and i moved it but now the bookwrym form ars nevaue is still flying to the postion where the inventory was i removed it and its very anooying please fix it thansk

**Comment by EB010-NL** [comment]
V1.0.3 Is my version and i didnt add any mods so far

**Comment by EB010-NL** [comment]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/143089225/965773f6-b8fb-4ec9-aa63-5e787d06b22b)

**Comment by Draxial** [comment]
How did you move the inventory? carryon? If that's the case, I think it messes with bookwyrm's path, and it keeps trying to find the inventory there; worst case scenario you either can re-add the inventory that he's looking for(or add something new, like a chest), or dispel the bookwyrm and redo the connection
