### ISSUE TITLE
All creative flight methods stop working at random intervals

### ISSUE THREAD

**Issue by BeastyCloak** [AllTheMods/VolcanoBlock#107]
This has been a complaint since early beta. Any ideas what causes this? It happens no matter the flight method.

**Comment by Draxial** [comment]
Can you check if you have the server.properties allow-flight=true? If it's single player I dunno if there's an option for that, but wondering if it would have something to do with the "enable cheats" button

**Comment by djnifos** [comment]
I had this problem when leaving the range of an RFTools Environment Controller.   Removing the controller fixed it.
