### ISSUE TITLE
starting island with house has no possibility for a fireproof boat

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/VolcanoBlock#11]
i chose the starting island with the house and therefore didn't have either type of wood for the fireproof boat. Did I miss something or is this still a mistake.

**Comment by Verathis** [comment]
You missed something. You can do "/skyblock spawn" and go back to the spawn island to get the necessary trees.

**Comment by Schrimpes** [comment]
I'm not sure if that's how it's intended. think on a server the spawn is probably protected

**Comment by Verathis** [comment]
It literally says to check spawn in the quest text, so it was definitely intended. How it's intended on servers, I have no clue.

![image](https://github.com/AllTheMods/VolcanoBlock/assets/30552734/2263e421-ff3c-4fff-84da-396b5e096d5e)

**Comment by Schrimpes** [comment]
it says "check your spawn SHIP", I understand that what is meant is that you should take the planks out of your ship, but no ship no planks ^^

**Comment by wyndman** [comment]
The same can be said for the bunker as well. I managed to cobblestone out to one of the box cars and ripped apart the chiseled wood from there. The alternative would also be sifting netherrack.

**Comment by oly2o6** [comment]
Fixed the description in 1.0.1 (pending)
