### ISSUE TITLE
ic2 recipe´s are Buggy

### ISSUE THREAD

**Issue by kontra1607** [AllTheMods/VolcanoBlock#110]
A few recipes in ic2 are buggy
![Screenshot 2023-08-26 160942](https://github.com/AllTheMods/VolcanoBlock/assets/75700554/aaada1c1-255e-49fb-93e1-c9a3fc781363)

**Comment by kontra1607** [comment]
![Screenshot 2023-08-26 161543](https://github.com/AllTheMods/VolcanoBlock/assets/75700554/d0d270f2-cd4f-4b16-b2d4-d5318da3aede)

![Screenshot 2023-08-26 161639](https://github.com/AllTheMods/VolcanoBlock/assets/75700554/3eaa375b-0a19-4845-8dd8-1a2a4efa324f)
![Screenshot 2023-08-26 161632](https://github.com/AllTheMods/VolcanoBlock/assets/75700554/1de8712d-4566-4655-aecc-fc09e32acf54)

**Comment by MPThLee** [comment]
If you mean multiple items on crafting recipe, It’s not bug. You should craft them with normal Minecraft crafting table or bulk crafter on ic2.

**Comment by Draxial** [comment]
@kontra1607 might be worth looking at https://github.com/TinyModularThings/IC2Classic/issues/317 
ic2 multi input recipes are indeed weird, not sure it there's much that we can do on our side
