### ISSUE TITLE
Why iron jetpacks not appear in jei anymore?

### ISSUE THREAD

**Issue by rodopoulos1** [AllTheMods/VolcanoBlock#111]
Why iron jetpacks not appear in jei anymore?
![image](https://github.com/AllTheMods/VolcanoBlock/assets/101236856/05604ae2-d529-4c69-9fd7-c0c8587ea907)

**Comment by Draxial** [comment]
It's a curse bug that for some reason corrupts some config files. Delete the ironjetpacks toml config and folder, and it should be fine

**Comment by Draxial** [comment]
#90
