### ISSUE TITLE
using a manasteel hoe crashes the game

### ISSUE THREAD

**Issue by GridCube** [AllTheMods/VolcanoBlock#114]
making and using a manasteel hoe automatically crashes the game

**Comment by DelusionalWizard** [comment]
Please send a crash report

**Comment by GridCube** [comment]
[crash-2023-09-16_20.16.42-server.txt](https://github.com/AllTheMods/VolcanoBlock/files/12641724/crash-2023-09-16_20.16.42-server.txt)
 here you go

**Comment by oly2o6** [comment]
Closing unless someone else can reproduce the issue

**Comment by LuciusV** [comment]
I also got crash on 1.0.7

[Uploading crash-2023-09-28_09.43.36-server.txt…]()

**Comment by LuciusV** [comment]
Same with Elementium hoe...

But Manasteel/Elementium/Terrasteel AIOT do not crash the game. And Terrasteel hoe simply doesn't work (right click does nothing)
