### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by LuciusV** [AllTheMods/VolcanoBlock#127]
I've found three recipes not working (there are no disabling scripts in kubejs folder for them, so I consider this is a bug):
1. Cake cannot be created by create pouring milk on cake base (which is also missing)
2. Quartz  cannot be infused to Rose Quartz in Mekanism infuser.
3. Roze Quartz cannot be polished in Mekanism Enrichment chamber.

**Comment by john13210** [comment]
they arent missing they just arent added bruh
and dont expect things from other packs to be in the one you play on

and for #1 what cake base ? there is one for blazing cake but not for normal one

**Comment by LuciusV** [comment]
Sorry, I realised that all those recipes are from "Create crafts and additions" which is not in the pack.
