### ISSUE TITLE
Crash after update, several issues. 

### ISSUE THREAD

**Issue by mwa206** [AllTheMods/VolcanoBlock#128]
I just updated to 1.06, game first crashed when interacting with Functional Storage 2x2 drawer.  Then after several relog and repeats, now Iron Jetpacks are no longer craftabel and exsisting jet pack is labeld as "undefined" and rendered unusable.

Tried to revert to old version, Iron Jet pack issue still persists.  

At this point the gam is unplayable.  

Updated from 1.03 to 1.06

**Comment by billbertking1** [comment]
Delete iron jetpacks config and report back
