### ISSUE TITLE
Missing recipe in Compacting Drawer.

### ISSUE THREAD

**Issue by Marinv9** [AllTheMods/VolcanoBlock#13]
In "Compacting Drawer", "Ore pieces" do not come together in four, but amethyst or something.

**Comment by PianoHallvard** [comment]
This is because for compacting drawers to operate as expected, the compaction recipes need to be two-way. Since the raw metals don't convert back into the pieces, the compacting drawer won't let you do that operation. Same goes for all else without cross compatibility
