### ISSUE TITLE
Orange Dye Chicken Next drop Crazy High

### ISSUE THREAD

**Issue by Wtfigohere** [AllTheMods/VolcanoBlock#132]
Orange Dye Chicken Next drop Crazy High.
No matter if its 1-1-1 or 10-10-10 after the 10~6 min first drop the "next drop" goes to a crazy long number EX:859:51567:00
All other dye chickens seem fine.

**Comment by billbertking1** [comment]
Fixed in a PR don't remember which lol probably #159
