### ISSUE TITLE
you can get BARRIER BLOCKS from ore laser

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#134]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/65425849/d05fdd8d-36d8-4186-85d2-025454d98ac6)

**Comment by john13210** [comment]
even if it says its just an empty tag it will spawn you this renamed barrier and you can place them no problem

**Comment by ChosenArchitect** [comment]
Sorry about that, I did search through the keywords and unfortunately I guess I didn't see it.
