### ISSUE TITLE
random reward for Energizing Rod (Nitro) quest isnt setup

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#135]
v1.0.7

![image](https://github.com/AllTheMods/VolcanoBlock/assets/65425849/9c1b60bf-7fbc-48c5-800d-5ef386c8d44d)

**Comment by TheBedrockMaster** [comment]
Any more information?

**Comment by john13210** [comment]
the item reward besides xp wasnt setup like in other quests and it was empty i think
