### ISSUE TITLE
if you dont plan on adding mythicbotany maybe hide the tools in jei that require it 

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#140]
alfsteel shovel , hoe , AIOT
![image](https://github.com/AllTheMods/VolcanoBlock/assets/65425849/b7e6a3a8-cfd0-416a-96b8-229c252e03ea)

**Comment by john13210** [comment]
talking about hiding stuff in jei , dragon egg is hidden
compressed soul sand from spirit mod is hidden

**Comment by billbertking1** [comment]
Unsure why dragon egg or soul sand from spirit is hidden, but have pr coming in soon to hide the tools.
