### ISSUE TITLE
Server crach after leaving a compact machine

### ISSUE THREAD

**Issue by Titinol** [AllTheMods/VolcanoBlock#142]
Hello, after exiting a compact machine, the server I am playing on crashes. This happens when using the command /tpx minecraft:overworld or the tool provided by compact machine.
[crash-2023-09-07_17.40.32-server.txt](https://github.com/AllTheMods/VolcanoBlock/files/12551116/crash-2023-09-07_17.40.32-server.txt)

**Comment by john13210** [comment]
change max tick time to 99999999
see if it fixes it
if not then -1

**Comment by Titinol** [comment]
Thank you for your response. It's was my fault this pack(and minecraft I think) is not compatible with the current version of java available on Debian12 this was my problems. 
I have changed my server on Debian11 JRE17 and no problems.
