### ISSUE TITLE
You can get a NaN amount of health which causes a lot of problems

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#145]
v1.0.7

so this is a 2 year old problem from 1.12.2 or something like this
a friend got hit by wilden with one of his attacks 
and i guess he was hit with an attack that would kill you instantly but it didnt and that caused him to have NaN amount of absorption

btw what kind of problems you cant do much at that broken state
like open your inv, open chests and stuff

there was a fix for that but the mod is only for 1.12.2 and the guy abbandoned it 
https://www.curseforge.com/minecraft/mc-mods/entity-nan-health-fix/files/2611882

**Comment by swet101** [comment]
I got a new sword and tried testing it out on a warden, i get a powdered snow freezing effect on me, i flew away from the island in panic and after the darkness goes away i am suddenly at NaN health. I suspect the Plague doctor enchantment had a hand in this.
[latest.log](https://github.com/AllTheMods/VolcanoBlock/files/12623878/latest.log)
no second log :(

**Comment by billbertking1** [comment]
> I got a new sword and tried testing it out on a warden, i get a powdered snow freezing effect on me, i flew away from the island in panic and after the darkness goes away i am suddenly at NaN health. I suspect the Plague doctor enchantment had a hand in this. [latest.log](https://github.com/AllTheMods/VolcanoBlock/files/12623878/latest.log) no second log :(

is there more files by chance in your logs folder? That latest.log seems to be cut off - or are you able to replicate it?

**Comment by swet101** [comment]
yeah there are more files in there, i used the search bar for the first log, im gonna post the 4 latest files
[2023-09-16-1.log.gz](https://github.com/AllTheMods/VolcanoBlock/files/12640914/2023-09-16-1.log.gz)
[2023-09-15-3.log.gz](https://github.com/AllTheMods/VolcanoBlock/files/12640915/2023-09-15-3.log.gz)

[2023-09-15-4.log.gz](https://github.com/AllTheMods/VolcanoBlock/files/12640912/2023-09-15-4.log.gz)
[2023-09-15-5.log.gz](https://github.com/AllTheMods/VolcanoBlock/files/12640913/2023-09-15-5.log.gz)
as for the replication, i've loaded a backup of my world and tried fighting warden again, and the sword seems to be the culprit, attacking the warden with it has a chance to give me freezing IV but doesn't produce the bug, i think in my case i got the effect two times and it lasted long enough to attempt to instakill me, but the baubley soul heart container got in the way to make my hp NaN

**Comment by oly2o6** [comment]
So if this is an issue that has not been fixed since 1.12 its not going to be something I can fix
