### ISSUE TITLE
Ars source going into AE interface crashes game

### ISSUE THREAD

**Issue by chadle01** [AllTheMods/VolcanoBlock#146]
So I wasnt intending for it to go into that AE interface but I guess it was too close to my source generation and sure enough it started filling up the AE interface, so I tried to give it somewhere to go by exporting it but the two states of source I saw in JEI were gas and liquid but those werent exporting it so i thought I'll break the interface and fill it up with something else so the source wont go in there, but as soon as I broke it, game instantly crashed. I tested it again to reproduce and it does.

Steps to reproduce

1. Place ME interface near source generation
2. After any amount of source is moved to ME interface, break the interface (does not matter if the ME interface is connected to a network or not)

Result: Game crash

I am running this on a linux server so it was the server that crashed not sure about how it would react with client only

looks like theres a source accepter from ars energistics in there maybe im supposed to use it with that somehow, but still I dont think doing it the wrong way should cause a game crash so reporting as a bug.
 I am attaching the crash report as well. Hope this helps thanks for all your awesome work on this modpack !
[crash-2023-09-09_00.35.04-server.txt](https://github.com/AllTheMods/VolcanoBlock/files/12564294/crash-2023-09-09_00.35.04-server.txt)

**Comment by john13210** [comment]
weird it doesnt crash for me , im on a server btw

**Comment by billbertking1** [comment]
Forwarded this to 90 - the mod dev, hopefully they have an idea as to what's going on

**Comment by 62832** [comment]
This should hopefully be fixed now, but I'm afraid I can't actually make a new release of Ars Énergistique until Ars Nouveau 3.17.12 is out. That version has supposedly been stuck in the scanning stages on CurseForge since yesterday, so I'm not sure yet how long it'll be until I can push my fix as well.
