### ISSUE TITLE
in the SPS quest the "Click me to learn how to build" even has wrong command

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#149]
v1.0.7

it should be something like this ->
/say Hi, @p!/create ponder mekanismgenerators:fusion_reactor_frame

but its just ->
/create ponder mekanism:sps_casing

so even if you add the structures to the ponder thing i dont think this will work

**Comment by oly2o6** [comment]
this actually works fine as its a command reward that auto triggers for the player, reminds me to add those in though
