### ISSUE TITLE
The command for "Click me to learn how to build" should be changed not as /say but as /msg or something else

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#150]
v1.0.7

this is ok in singleplayer but in multiplayer it just sends a message in chat and everyone can see it

**Comment by john13210** [comment]
or if you want it to be fancy you can have it as 
/tellraw @p {"text":"Hi to see how its built use /create ponder mekanismgenerators:fusion_reactor_frame","color":"blue"}

this will show a blue message in chat thats per player

i use https://minecraft.tools/en/tellraw.php
to make good looking messages in chat

**Comment by oly2o6** [comment]
Fixed in upcoming update
