### ISSUE TITLE
powah quests for dischargers , cables and ender cells arent depended on the quest with tier lower  but on crystals

### ISSUE THREAD

**Issue by john13210** [AllTheMods/VolcanoBlock#152]
v1.0.7

almost all of them are like that so why leave 3 items like that ?

![image](https://github.com/AllTheMods/VolcanoBlock/assets/65425849/80ba98e2-6050-440c-8c47-45ada6e3f3d1)

**Comment by oly2o6** [comment]
No idea, but its also not really an urgent issue, so ill close this off but add it to my internal notes
