### ISSUE TITLE
IF Laser Drill Empty Tag Items AKA Barrier Blocks

### ISSUE THREAD

**Issue by ChosenArchitect** [AllTheMods/VolcanoBlock#156]
Version 1.0.7

When using the Ore Laser Drill in the End Highlands Biome you will get "Empty Tage: Forge:raw_materials/Azure_silver" items that are Barrier Blocks and if placed you won't be able to break them without going into creative mode. 
![image](https://github.com/AllTheMods/VolcanoBlock/assets/35053440/eaf2ddcb-c2dd-4b2a-a02b-b20a82e7ed51)

**Comment by john13210** [comment]
hello mr youtuber
i already reported this
https://github.com/AllTheMods/VolcanoBlock/issues/134

**Comment by ChosenArchitect** [comment]
Sorry about that, I did search through the keywords and unfortunately I guess I didn't see it.

**Comment by billbertking1** [comment]
#159
