### ISSUE TITLE
IC2 Electric Furnace can't smelt AllTheOres Tin & Lead Dust

### ISSUE THREAD

**Issue by sreny1** [AllTheMods/VolcanoBlock#157]
The IC2 Furnace is missing a recipe to smelt Tin & Lead Dust from AllTheOres

**Comment by john13210** [comment]
works on 1.0.7 , are you talking about that normal electric furnace ? not induction or anything ? it works for me

**Comment by sreny1** [comment]
i am on 1.0.7
regular electric furnace for me doesnt have a recipe to smelt those 2 dusts

**Comment by sreny1** [comment]
nvm, its working now.. guess it was bugging earlier

litterally setup 12 of those to process all my ores and those 2 were not working for some reason :(
