### ISSUE TITLE
The discord link in the AllTheModium book is expired/broken

### ISSUE THREAD

**Issue by Jordan-Cottle** [AllTheMods/VolcanoBlock#16]
It links to `https://discord.com/invite/K5FBPYa` which isn't valid (at least for me?)

![image](https://github.com/AllTheMods/VolcanoBlock/assets/37338122/d93b7db0-a3e8-4867-b554-e04348ad8c3f)

The link in this repo's README is `https://discord.gg/3paFjuRfz9`

**Comment by oly2o6** [comment]
Fixed in 1.0.1 (pending)
