### ISSUE TITLE
Wither builder wont work in compact machines unless standing in it and not chunk claimed

### ISSUE THREAD

**Issue by King-Idealist** [AllTheMods/VolcanoBlock#164]
The wither builder wont work in the compact machine unless you are standing inside and the chunk is not claimed or force loaded, also you cant chunk claim it inside and leave otherwise it will completely stop until the whole game is reset.

**Comment by sreny1** [comment]
probably you would have to allow fake players in your claim for it to work
try putting this ID into the "Allied Fake Player Names/IDs" list in your FTB Teams settings:
ec5b5875-ebb5-4b47-833b-0de37ac9e6d7

Its the ID that Industrial Foregoing uses for their machines, as found here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/fc4c286af75d164d213c86ac1c9df8cfa4e49977/src/main/java/com/buuz135/industrial/utils/IFFakePlayer.java#L43

**Comment by oly2o6** [comment]
follow instructions above
