### ISSUE TITLE
Mekanism Enrichment Chamber

### ISSUE THREAD

**Issue by bloo1147** [AllTheMods/VolcanoBlock#165]
Enrichment chamber, and all variants, will sometimes double process and not remove raw ore from it's inventory.  Not really sure what could be causing the issue.

**Comment by billbertking1** [comment]
I'm fairly certain it needs a minimum of 3 ore to work - does it work with 3+?

**Comment by bloo1147** [comment]
> I'm fairly certain it needs a minimum of 3 ore to work - does it work with 3+?

Each raw ore will process down into two dust.  It just happened again.  The iron is processing but the lead was double processed twice and the machine doesn't register the raw ore is there.  I can pull it out, but the machine refuses to process it even if put back in.

![2023-09-20_15 51 19](https://github.com/AllTheMods/VolcanoBlock/assets/63519058/506e4fb3-ef78-482e-b89d-1b949fd9f322)

**Comment by bloo1147** [comment]
> I'm fairly certain it needs a minimum of 3 ore to work - does it work with 3+?

looks like you were right and I just wasn't paying attention to the recipe. Not used to it needing 3 XD
