### ISSUE TITLE
Unable to Craft IC2 "Plasma Core" or Create Auto-Crafting Pattern

### ISSUE THREAD

**Issue by DeepFriedAndDead** [AllTheMods/VolcanoBlock#166]
As title says, unable to craft or set up auto crafting pattern for IC2 Plasma Core required for end game and ATM Star.

Have tried manual crafting, JEI recipe request, create auto-mated shape crafting, etc. and unable to craft Plasma Core. 

![Plasma Core - Can't Encode Pattern](https://github.com/AllTheMods/VolcanoBlock/assets/120140937/2c318ff7-3096-4493-93a5-7e03741c99b4)
![Plasma Core - Can't Craft](https://github.com/AllTheMods/VolcanoBlock/assets/120140937/0c8dd09c-c906-4b2d-af1f-0cccb7ee7c38)
![Plasma Core - Recipe](https://github.com/AllTheMods/VolcanoBlock/assets/120140937/bb8816d5-9553-4532-8f6d-7d41e2fe64d2)

**Comment by DeepFriedAndDead** [comment]
![Plasma Core - Can't Craft 2](https://github.com/AllTheMods/VolcanoBlock/assets/120140937/4b632ee3-3193-4173-ac73-54e93c230b2b)

**Comment by billbertking1** [comment]
Use vanilla crafting table to manually craft it or use the "Bulk Crafter" I think it's called from IC2C. A rundown of how to use it is pinned in the discord, #volcano-general
