### ISSUE TITLE
Spirit Compressed Soul Sand Missing in JEI

### ISSUE THREAD

**Issue by ChosenArchitect** [AllTheMods/VolcanoBlock#167]
Version 1.0.7

The only way to make the block of Soul Steel you use the compressed block from the Spirit mod itself so you can't use the compressed block of Soul Sand. So when looking for what the mod says to use it seems it is hidden jei.

**Comment by john13210** [comment]
he's fixing the problem with hidden compressed soul sand from spirit mod (and dragon egg) in jei

**Comment by oly2o6** [comment]
Fixed in next ver
