### ISSUE TITLE
buying animal spawn eggs from market block 

### ISSUE THREAD

**Issue by PikachuGabe** [AllTheMods/VolcanoBlock#17]
as it seems that i cannot get any animals to spawn no matter what i do, i think it would be a good idea to do the same thing done in some popular skyblock modpacks that you can buy spawn eggs for the peaceful mobs through the market block. ive been playing on a network that has had the pack for about a day and while people have made a lot of progress, the only mobs anyone has gotten to spawn are chickens from resourceful chickens.

**Comment by oly2o6** [comment]
So you need to set the grass platform up a few blocks above lava and a few chunks out, but ill get mobs craftable in a future update!
