### ISSUE TITLE
when I went to get a reward from ftb quests got this error

### ISSUE THREAD

**Issue by EmmaRavens** [AllTheMods/VolcanoBlock#172]
ATM9 0.1.7
Open FTB Quests  > Part 1: Getting Started > Functional Storage > Common Reward (Middle Chest)

![image](https://github.com/AllTheMods/VolcanoBlock/assets/12566399/7416fe94-dec3-4266-b290-337f797133ca)

`/sgear_random_gear @p silentgear:paxel 3`

**Comment by EmmaRavens** [comment]
happened again with Kill 10 Spiders Common Reward 

![image](https://github.com/AllTheMods/VolcanoBlock/assets/12566399/a4755c2a-9da5-4853-aece-15e5b1ca154d)

**Comment by oly2o6** [comment]
this isnt atm9
