### ISSUE TITLE
Lava burn time

### ISSUE THREAD

**Issue by fwaaade** [AllTheMods/VolcanoBlock#175]
According to this:

https://github.com/AllTheMods/VolcanoBlock/blob/9c86e6a11fd7b79b53ea79abbac85eb3e31e7df8/kubejs/startup_scripts/itemModification.js#L1-L5

Lava does not have a burn time, so you can't use it in furnaces and some generators.

This line is inaccurate then:

https://github.com/AllTheMods/VolcanoBlock/blob/9c86e6a11fd7b79b53ea79abbac85eb3e31e7df8/config/ftbquests/quests/chapters/mekanism.snbt#L1708

since the lava buckets can't work with fuelwood heaters since they have no burnTime.

IC2 lava cells also still have a burn time, which is probably unintentional.

Either you make IC2 lava cells not burn as well (I think `event.modify(['minecraft:lava_bucket', 'ic2:cell_lava'], item => {` would do it), as well as changing the mekanism quest description

Or you just allow lava to be burnt. Lava in furnaces and in fuelwood heaters doesn't seem too powerful. Maybe you can have it so a bucket of lava only smelts 8 items instead of 100 or something.

**Comment by oly2o6** [comment]
Fixed in next update!

**Comment by fwaaade** [comment]
So are ic2 lava cells burning intentional? They work effectively like buckets (you get the cell back and can fill them with a mekanism tank), just a bit harder to automate to keep 1 in the fuel slot
