### ISSUE TITLE
Magma Mycelial Generator still craftable

### ISSUE THREAD

**Issue by OhBrod** [AllTheMods/VolcanoBlock#18]
Should probably be removed like the other lava gen.

![image](https://github.com/AllTheMods/VolcanoBlock/assets/44421269/c1569910-c599-4328-914d-a0162873cc90)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/44421269/85dab81e-a482-485d-9b2b-e202a675d3d6)

**Comment by PianoHallvard** [comment]
I think this one's intentional, since to get the mycelial generators you have to tier up through IF, and at that point you would've set up self sufficient power anyway
