### ISSUE TITLE
Can't connect to a server due to some Registry errors due to resource chickens mod

### ISSUE THREAD

**Issue by Gh3ttoboy** [AllTheMods/VolcanoBlock#180]
i have come across a bug i think.
i assume just deleting the Resoucerchicken.config on the server will let it redownload and possibly fix this issue with the server
![image](https://github.com/AllTheMods/VolcanoBlock/assets/6478174/4b861000-11a6-4054-bb65-e1a364f9fd6c)

**Comment by oly2o6** [comment]
No idea what causes this but redownloading the update fixes it, its a rare issue
