### ISSUE TITLE
Problem with "Crafting Tweaks" mod

### ISSUE THREAD

**Issue by Oofer495** [AllTheMods/VolcanoBlock#19]
When using the "compress item" keybind you can compress items even without having the right amount of items/resources for it. 

For example; pressing "J" as the compress item keybind on 1 pebble will give you 1 cobblestone even though the recipe is for four. If you press continually it will compress the cobble more and more until reaching "9x compressed" without having the thousands of cobblestone needed in the first place.

**Comment by Mitchell5200** [comment]
already reported to the dev, and fixed, will be fixed in the next pack update or two
https://github.com/TwelveIterationMods/CraftingTweaks/issues/202

**Comment by oly2o6** [comment]
Fixed in 1.0.1 (pending)
