### ISSUE TITLE
JEI says you can make obsidian in any type of barrel when it only works with stone barrels

### ISSUE THREAD

**Issue by lexiconvict** [AllTheMods/VolcanoBlock#20]
Not sure if this is a JEI issue or an Ex Nihilo one but it would probably help some players if it was specific in JEI.

**Comment by oly2o6** [comment]
Yeah this would be better directed to the ex nihilo github, ill close it here

**Comment by lexiconvict** [comment]
Sounds good, thank you for the feedback.On Jul 31, 2023 1:36 PM, oly2o6 ***@***.***> wrote:
Yeah this would be better directed to the ex nihilo github, ill close it here
