### ISSUE TITLE
Aluminum Ore from @AllTheOres cannot be inserted into the Macerator from @IC2 Classic

### ISSUE THREAD

**Issue by lexiconvict** [AllTheMods/VolcanoBlock#21]
Macerator will only accept Aluminum Ore from @IC2 Classic. Not sure if this is intended or a bug.

**Comment by oly2o6** [comment]
This should have been fixed but we will look into it to confirm!

**Comment by lexiconvict** [comment]
I'm on the latest forge version I believe (43.2.14), playing today and it wasn't working for me. Also, a bit unrelated, but it seems like the only way to get coal dust to make carbon fiber for @IC2 Classic is to use @Mekanism or @Integrated Dynamics. I'm not sure if that is intended or not.Cheers,-JoshOn Jul 31, 2023 1:36 PM, oly2o6 ***@***.***> wrote:
This should have been fixed but we will look into it to confirm!

**Comment by oly2o6** [comment]
Yep just confirmed that some things with the macerator are being missed with unification, we will get this sorted!

**Comment by lexiconvict** [comment]
Right on, thanks for all your hard work👍On Jul 31, 2023 1:44 PM, oly2o6 ***@***.***> wrote:
Yep just confirmed that some things with the macerator are being missed with unification, we will get this sorted!

**Comment by oly2o6** [comment]
alright just tested this out and it appears to be all fixed! will be going into 1.0.1, thanks for letting me know of these, I also threw in ic2 cobble>gravel>sand>dust for the macerator whilst I was at it ;)

**Comment by lexiconvict** [comment]
That's quick work! Awesome, looking forward to the changes:)On Jul 31, 2023 5:01 PM, oly2o6 ***@***.***> wrote:
alright just tested this out and it appears to be all fixed! will be going into 1.0.1, thanks for letting me know of these, I also threw in ic2 cobble>gravel>sand>dust for the macerator whilst I was at it ;)

**Comment by lexiconvict** [comment]
Just a heads up, Aluminum Ore still appears not to have an AllTheOres version and cannot be inserted into the Macerator from IC2 Classic. I'm updated to 1.0.1, and I do appreciate the other changes to the Macerator very much though!

-Josh
________________________________

**Comment by lexiconvict** [comment]
Sorry, disregard that. There IS an AllTheOres Aluminum Ore, however, it cannot be inserted in the Macerator. JEI says only Aluminum Ore from IC2 Classic can be put in, however, there is no recipe shown to obtain the IC2 Aluminum Ore.
________________________________
