### ISSUE TITLE
Bug with Quest Book

### ISSUE THREAD

**Issue by rodopoulos1** [AllTheMods/VolcanoBlock#22]
The quest book not accept this Log
![image](https://github.com/AllTheMods/VolcanoBlock/assets/101236856/b4b5c80f-25ea-488a-85cd-3f1dcd211aeb)

**Comment by oly2o6** [comment]
So you are not supposed to play on the original island, there are signs inside that state that it is the spawn island and not to be based on, please do /skyblock gui 
From there you can select a playable island

**Comment by rodopoulos1** [comment]
Sorry
