### ISSUE TITLE
ATM VB Stuck on loading screen

### ISSUE THREAD

**Issue by Swxted** [AllTheMods/VolcanoBlock#25]
So basically every time i try loading in, it just stays on the loading screen with stars, I've waited 10 mins on that screen and nothing happens still, Anyone know the issue?

**Comment by Swxted** [comment]
![Screenshot 2023-07-31 204838](https://github.com/AllTheMods/VolcanoBlock/assets/141089046/b8afced3-2ac5-408a-b31f-46b0792c8b86)

**Comment by Swxted** [comment]
> 
it needs that much ram??? i only have 16 gb of ram.

**Comment by Shadedstalker2** [comment]
@Swxted it does not need that much ram try reinstalling or checking java version or do some args which can be found in the discord

**Comment by Swxted** [comment]
i added the args and it didnt help sadly

**Comment by Lekkawokke** [comment]
After reinstalling i am also stuck in loading screen.

**Comment by Mogwump** [comment]
In ATM7TTS, I had an issue where if I clicked or alt-tabbed out of the game during the loading screen then it would stop responding. Same when loading any world/server. I haven't had the problem for newer packs, but maybe try not clicking the window at all and see if you load into the main menu?

**Comment by Exblosis** [comment]
It works for me after I disable rubidium for the first modpack launch and after the first launch you can re-enable rubidium

**Comment by oly2o6** [comment]
Odd, going to close this but if anyone has the issue where rubidium removal does not fix it please let us know
