### ISSUE TITLE
No warped/crimson wood available on vivid grass starter island

### ISSUE THREAD

**Issue by osirisgothra** [AllTheMods/VolcanoBlock#27]
The 'getting started' chapter questbook quest for exploration suggests that you need only explore your island further to be able to make a boat -- not possible on the terracotta/vivid grass island as you are given none. The only way to complete this quest is later on when you can infuse netherrack with mekanism or have nether seeds AND nature seeds in mystical agriculture. It might we worth noting that this ruins competition between teams - teams starting on this island are stuck not being able to explore early game while the other teams proceed to jump ahead because they can. If this is intended, a warning on the starter screen might be nice.

**Comment by Vexsanity** [comment]
I was told by the pack creator that this island and the bunker are considered "harder". You can solve your problem by building a cobble gen and cobble bridging to a near by structure that looks like train tracks, they will have the wood you need but you'll have to chisel it back to its normal plankiness

**Comment by Seegras** [comment]
Another option is to sieve for warped or crimson mycelium seeds, then you can grow it.

**Comment by oly2o6** [comment]
> Another option is to sieve for warped or crimson mycelium seeds, then you can grow it.

This is correct, then you bone meal it
