### ISSUE TITLE
Geothermal Generator Unit uncraftable due to heat generator being disabled

### ISSUE THREAD

**Issue by KingOnoi** [AllTheMods/VolcanoBlock#28]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/77258154/18baca5a-6499-40c1-a552-2f480edae79f)

The heat generator is required for the mekanism meka-suit for the upgrade that reduces fire damage taken, but the heat generator is disabled since its lava > rf, can you swap it out for a different item so we can still get that suit upgrade please

**Comment by Shadedstalker2** [comment]
fixed in next update
