### ISSUE TITLE
Recipe for RFTools Builder

### ISSUE THREAD

**Issue by RyuKajiya** [AllTheMods/VolcanoBlock#29]
What is the intention of the hard recipe for the RFTools builder? because it is a nice tool for base building with the blank shape card. so if the only intention was gating the super quarry mode of it it would be better to make the first quarry card recipe harder and leave the builder to be able to use it for base building

**Comment by Seegras** [comment]
Same with the exchange gadget, it's mostly a tool for changing builds. Besides, what's the big advantage otherwise? Being able to maybe mine ores, which are not present in the overworld and the nether anyway?

**Comment by oly2o6** [comment]
both of these are fixed in the next release! I originally ported them over as I had other plans for how the pack would play out but you are right, these make no sense! I also did it for the turtle recipe
