### ISSUE TITLE
Feeding Trough Doesn't Feed/Breed Resource Chickens

### ISSUE THREAD

**Issue by HumdrumPanic** [AllTheMods/VolcanoBlock#30]
Mod pack Version 1.00

Issue:
The _Feeding Trough_ from _Farming for Blockheads_ doesn't feed/breed _**Resource Chickens**_ when filled with wheat seeds.

Expected:
Should be seeing, after breeding cool downs are expired, that the trough will auto feed the **_resource chickens_** within default range (8 Blocks) putting them into love mode resulting in auto breeding

Appears to be a mod issue:
https://github.com/TwelveIterationMods/FarmingForBlockheads/issues/171

Followed through with **_Resource Chickens_**:
https://legacy.curseforge.com/minecraft/mc-mods/resource-chickens/issues/18

**Comment by oly2o6** [comment]
As this is a mod issue im going to close this off
