### ISSUE TITLE
In 1.0.1 version pack, platinum ore hammer in a create mixer disappears after 1 ore is processed. 

### ISSUE THREAD

**Issue by Amunsul** [AllTheMods/VolcanoBlock#33]
if manually used the platinum ore hammer works fine, but if put into a create mixer setup it disappears after processing a single ore. Not sure if this affects the other ore hammer variants but it definitely does the platinum version. This is not an issue in 1.0.0.

**Comment by AerosAtar** [comment]
I've done some personal testing and upgrading Create to 0.5.1**c**  appears to fix this issue, at least for ore hammers.

**Comment by oly2o6** [comment]
Yeah so there are crash issues with 0.5.1c right now so I cant update that mod

**Comment by oly2o6** [comment]
Going to close for now as it is confirmed fixed in the next version of create
