### ISSUE TITLE
Smelting silver dust in a smelting factory produces IC2 silver

### ISSUE THREAD

**Issue by jmgilman** [AllTheMods/VolcanoBlock#35]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/2308444/ed452b2b-6c30-4047-948e-a3a61ae8e0a0)

I'm assuming these should be AllTheOres silver.

**Comment by MPThLee** [comment]
I'm also able to reproduce. VB 1.0.1.
Temporal solution is convert ic2 silver to block or nugget (which will produce ATM one) and make it to ingot again.
![image](https://github.com/AllTheMods/VolcanoBlock/assets/26970092/8bced966-10db-4b8a-87fb-54d80ccc5aec)

**Comment by MPThLee** [comment]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/26970092/ba6e896c-87eb-4aaa-9618-90af0c86afaa)
Well, Silver is solved somehow, but I'm getting issue with tin instead.

**Comment by Draxial** [comment]
This will be hopefully fixed in the next release!

**Comment by Draxial** [comment]
I believe this has been fixed on 1.0.4, if you still have some issues, please reopen the ticket!
