### ISSUE TITLE
Client crash with rftools 

### ISSUE THREAD

**Issue by Warzer1** [AllTheMods/VolcanoBlock#36]
atmVB 1.0
crash report https://mclo.gs/v0eVZ9I
Playing with a local server and client on same pc
when using module storage with a T3 storage card loaded and locked.
shift clicked a gold nugget and stone button into the storage and a second or 2 later it crashes.
sometimes it crashes just opening the interface, sitting in the interface or few seconds after closing interface. 
its not 100% consistent with when it will crash. 
Edits:
Might also be rft tablet related as i had that in my inventory as well, but wasn't using it.
after i stashed the tablet in another chest the crashes stopped at least for now.
its been a bit and since i stored the tablet it hasn't crashed again.

**Comment by oly2o6** [comment]
Report to mod author
