### ISSUE TITLE
no recipes miniature portal for dimensional seed

### ISSUE THREAD

**Issue by Fellal1** [AllTheMods/VolcanoBlock#39]
no recipes miniature portal for dimensional seed on 1.0.1

**Comment by Draxial** [comment]
This will be hopefully fixed in the next release!

**Comment by Draxial** [comment]
I believe this has been fixed on 1.0.4, if you still have some issues, please reopen the ticket! Remember that the mini portal and the seed itself, the spirit crafting is directional! Check the seed's quest description for more info.
