### ISSUE TITLE
Minecraft freezes when loading a new world

### ISSUE THREAD

**Issue by Livciak** [AllTheMods/VolcanoBlock#45]
Hi!

I am having a problem loading a new world. At the very beginning, it didn't want to load Minecraft itself, but I fixed that, and now every time I try to load a world Minecraft freezes, and I can't do anything.

1. I updated my graphic drivers;
2. Increased Virtual Memory;
3. Minecraft has around 20GB RAM to use;
4. Reinstalled Minecraft and modpack;
5. Other modpacks work flawlessly;
6. I closed unnecessary programs;
7. Lower graphic settings;
8. Java is up to date;
(I might have forgotten about something I did but I used many methods)

I did everything and it still doesn't work, so idk what I can do to fix this issue...

**Comment by RobertLSnead** [comment]
same here...
no updates for mine...

**Comment by Livciak** [comment]
> same here... no updates for mine...
> 
> EDIT: killing minecraft and retrying seems to work, not sure why the first go around it crashes...

Not for me... I tried many times
