### ISSUE TITLE
Mistake in Moving Liquids quest in Part 1: Getting Started

### ISSUE THREAD

**Issue by Tismas** [AllTheMods/VolcanoBlock#46]
It says
"Using piece of dirt on full barrel of water gives you clay!"
But dirt gives you mud, it should be "piece of dust"

**Comment by billbertking1** [comment]
#12 known issue

**Comment by AerosAtar** [comment]
I am still seeing this in 1.0.1, even when I start a new world.

**Comment by oly2o6** [comment]
so its not that dirt should give clay, its that the quest is wrong, which is why its still working as before, its dust that gives clay which was fixed in the quest
