### ISSUE TITLE
Mekanism tank gets deleted when crafting Create dough

### ISSUE THREAD

**Issue by caiomuniz** [AllTheMods/VolcanoBlock#48]
When I was using the Create recipe to get some slime balls, I used a basic tank full of water to batch craft a bunch of dough, but when I crafted the first one, the tank simply got deleted completely.

**Comment by AerosAtar** [comment]
Likely the same issue as #33. 

There is this on the Create github - https://github.com/Creators-of-Create/Create/issues/5196 - so it might actually be a recently-introduced issue with Create (I'm fairly sure these kinds of recipes worked fine in earlier versions of Create)?
