### ISSUE TITLE
Can we have a way to produce Xycraft gems outside of Alchemistry

### ISSUE THREAD

**Issue by BeastyCloak** [AllTheMods/VolcanoBlock#53]
It makes for a good decorative block and is really limited going via alchemistry. A better way (miner, sieves, other ideas?) would be appreciated.

Thanks!

**Comment by Draxial** [comment]
This is being looked into, thank you for the suggestion!

**Comment by Draxial** [comment]
I believe this has been fixed on 1.0.4, if you still have some issues, please reopen the ticket!
