### ISSUE TITLE
Chicken resources incorrectly tagged

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/VolcanoBlock#56]
- silicon chicken exists, silicon exists, but it can neither be converted into, nor does it produce anything
- awakened draconium and draconium do not exist (no draconic evolution mod)
- quart enriched iron is misspelt and quartz enriched iron does not exist (no refined storage mod).
- water and lava chicken: they appear to work, couldn't figure out how to create them yet.

**Comment by oly2o6** [comment]
> * awakened draconium and draconium do not exist (no draconic evolution mod)
> * quart enriched iron is misspelt and quartz enriched iron does not exist (no refined storage mod).
These are intended to not be craftable, but they are still in JEI as the mod adds support to the mods natively


> * silicon chicken exists, silicon exists, but it can neither be converted into, nor does it produce anything
> * water and lava chicken: they appear to work, couldn't figure out how to create them yet.
Silicon is a bug, water/lava are potentially bugs but it might also be not knowing how they are crafted

**Comment by oly2o6** [comment]
#55

**Comment by Karma-Fox** [comment]
I was able to fix the Osmium chicken by changing the ingot to the alltheores version within the resource chickens config file for osmium. And draconium chickens just need to be disabled in their configs.

**Comment by Draxial** [comment]
@Karma-Fox Thank you! we didn't knew about the osmium one. I also disabled the quartz enriched iron and the draconium ones as well.
