### ISSUE TITLE
Mekanism Wind Generator not viable as first generator

### ISSUE THREAD

**Issue by The-Forge-Master** [AllTheMods/VolcanoBlock#59]
Part 1: Getting Started suggests I could use the Mekanism Wind Generator as a first power source, but its recipe requires a metallurgic infuser, which requires power.

**Comment by enigmaquip** [comment]
Mekanism machines can be powered by Redstone by putting it in the power slot

**Comment by The-Forge-Master** [comment]
Perhaps change it over to the Powah furnator? It's definitely the best coal generator, as it doesn't continue burning while the system is full on energy.

**Comment by Trontastic** [comment]
You can just start with coal generator to make those ingredients then switch to wind generator
