### ISSUE TITLE
Animals wont spawn

### ISSUE THREAD

**Issue by Joly0** [AllTheMods/VolcanoBlock#60]
I have spawned on the island with the house and played a while there and am now trying to get animals to spawn.
I have created a small island about 30 blocks away from my main island and covered it with grass blocks but animals wont spawn there. I have even elevated it a few blocks above the lava, as someone else suggested in another issue, but no matter what, animals dont spawn. Though monsters do

**Comment by AerosAtar** [comment]
It can take a long time. It took around six hours or so for a single cow to spawn for me, and I haven't seen a single additional spawn since (which is a lot more than six more hours). You might want to check nearby spawned structures, too, as they can end up with chickens in them which count toward the spawn cap if they are within range.

**Comment by Seegras** [comment]
ars nouveau has methods of conjuring islands with different biomes, as well as a tablet of summon animals. And of course, as soon as you have one chicken, you can make the golden egg and produce delightful dirt.

**Comment by Trontastic** [comment]
They do spawn, you just have to remove the others that spawned already because there is a very low limit how many can spawn (3-4 for me). You can use Animal Capture Net to store for later.

**Comment by DelusionalWizard** [comment]
> I have spawned on the island with the house and played a while there and am now trying to get animals to spawn. I have created a small island about 30 blocks away from my main island and covered it with grass blocks but animals wont spawn there. I have even elevated it a few blocks above the lava, as someone else suggested in another issue, but no matter what, animals dont spawn. Though monsters do

Try delightful dirt
