### ISSUE TITLE
processing alltheores silver dust on a Thermal Redstone Furnace produces IC2 silver ingots

### ISSUE THREAD

**Issue by GridCube** [AllTheMods/VolcanoBlock#61]
processing the silver chunks on a Thermal Pulverizer produces "alltheores:silver_dust" which cooked on a Thermal Redstone Furnace produces "ic2:silver_ingot", which when turn into nuggets becomes "alltheores:silver_nuggets", which then combine into a "alltheores:silver_ingot", this makes it impossible to store silver directly from the redstone furnace into a compacting drawer

**Comment by MPThLee** [comment]
Very similar to #35 but on Redstone Furnace.

**Comment by Draxial** [comment]
This will be hopefully fixed in the next release!

**Comment by Draxial** [comment]
I believe this has been fixed on 1.0.4, if you still have some issues, please reopen the ticket!
