### ISSUE TITLE
No recipe for Powah - Magmator and Thermo Generator - V1.0.1

### ISSUE THREAD

**Issue by waechtet** [AllTheMods/VolcanoBlock#63]
There are no recipes for both the Powah Magmator and Thermo Generator. Don´t know, if this is intended, but i would assume power generation based on lava (in a volcano) would normally be allowed ;-)

**Comment by Seegras** [comment]
this is most probably intended. All lava-based methods of power-generation have been disabled.

**Comment by waechtet** [comment]
Ok, then i hav to use the other methods. Thx.
