### ISSUE TITLE
Issue AE2 Middle Mousewheel Crafting Request

### ISSUE THREAD

**Issue by blowedd** [AllTheMods/VolcanoBlock#64]
Hey, does anyone know the shortcut for the autocrafting request in a terminal ? I ve tried everything, shift + mouswheel, shift + RC, shift + LC but nothing seems to work, i have to manually go to "only craftable" and request it manually. I tried to change the keybinds for middle mouseclick but nothing worked so far

![Unbenannt](https://github.com/AllTheMods/VolcanoBlock/assets/142232895/bc6cf51f-1605-4bb5-bf37-a73ff44ed443)

**Comment by BeastyCloak** [comment]
Get rid of the middle click key conflict and it works fine.

**Comment by blowedd** [comment]
done that, didnt work, there no keybind on the middleclick in the options
