### ISSUE TITLE
Squat Grow not working

### ISSUE THREAD

**Issue by kylebro78** [AllTheMods/VolcanoBlock#66]
Installed the pack and the crouch grow mechanism isn't working currently for me.  Any ideas what could be causing this?  

Thanks

**Comment by RGLHero** [comment]
i am having this issue as well

**Comment by PinkReindeer** [comment]
Me too

**Comment by pGommes** [comment]
Needs a water filler in hand for it to work, the application has not changed on admission!

**Comment by RGLHero** [comment]
can confirm having a hoe in your hand makes the fast grow work

**Comment by Draxial** [comment]
Thanks everyone for reporting this and sorry for the trouble! We fixed it in the hotfix release 1.0.3 . Please report any new issues, thank you!
