### ISSUE TITLE
Allthemodium Alloy Paxel not mining tool for apotheosis

### ISSUE THREAD

**Issue by Sativalord** [AllTheMods/VolcanoBlock#68]
Every other paxel is considered a mining tool in the Apotheosis reforge but the allthemodium alloy paxel is considered a weapon
![alloy paxel](https://github.com/AllTheMods/VolcanoBlock/assets/142300716/23df7e12-7982-4367-9711-bd8950c5fa35)
![awakened paxel](https://github.com/AllTheMods/VolcanoBlock/assets/142300716/0e5526e9-1dbb-46e1-be07-44ae79a81385)
![paxel](https://github.com/AllTheMods/VolcanoBlock/assets/142300716/b7b507e8-2e74-46ae-a782-2c7c6eb0dffa)

**Comment by oly2o6** [comment]
@thevortex
