### ISSUE TITLE
When smelts bronze dust to bronze

### ISSUE THREAD

**Issue by rodopoulos1** [AllTheMods/VolcanoBlock#70]
When smelts bronze dust to bronze the bronze tranform to Bronze from ic2 i dont know why
![image](https://github.com/AllTheMods/VolcanoBlock/assets/101236856/d704669a-b356-45f5-baf5-0dd6ea056137)

The correct is from alltheores correct?

Edit: Im smelting the bronze on Ultimate Smelting factory from mekanism

**Comment by Draxial** [comment]
@rodopoulos1 could you check if this still happens on 1.0.4? I just tested and it's not happening anymore:
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/f5d97069-9909-41c6-89e9-45f59931a737)
