### ISSUE TITLE
Crashing modpack ingame when request some items in AE2

### ISSUE THREAD

**Issue by rodopoulos1** [AllTheMods/VolcanoBlock#71]
Crashing modpack ingame when request some items in AE2, when i click fast on Jei ctrl + Click and press start ons recipes very fast on mouse click modpack crashes!

[crash-2023-08-16_14.49.20-client.txt](https://github.com/AllTheMods/VolcanoBlock/files/12362167/crash-2023-08-16_14.49.20-client.txt)

**Comment by Draxial** [comment]
Could you remove modern fix and see if this happens again?
