### ISSUE TITLE
Create Chicken Data Model not possible

### ISSUE THREAD

**Issue by Taareax** [AllTheMods/VolcanoBlock#72]
It is not possible to create a chicken data model because there only exists Chickens from Resource Chickens Mod.

**Comment by DelusionalWizard** [comment]
> 

Vanilla chickens spawn naturally from delightful dirt

**Comment by Draxial** [comment]
@DelusionalWizard thanks, this will actually fix/help with #109 when we add the forge:chicken tag to the modpack!
You can use the chickens that spawn with the delightful grass for both occultism and neural networks then.
