### ISSUE TITLE
All the Dust Blocks to go with AllTheOres?

### ISSUE THREAD

**Issue by MaulJunior** [AllTheMods/VolcanoBlock#74]
After seeing the utility of IC2C Dust Blocks, would it be possible to add Dust Blocks for all the AllTheOres, to better allow for mass dust smelting? The Dust Blocks are a fantastic addition, and it would be a helpful addition to have for, well, all the ores in both smelting and mass storage.

not looking for compressed dust blocks, but Osmium, Lead, etc Dust Blocks would be really REALLY nice to have.

**Comment by Draxial** [comment]
That is an interesting idea, could you please submit it to the alltheores github? it'll most likely need some more programming than just simple kubejs addition, thanks for the suggestion!
