### ISSUE TITLE
iesnium impossible to get?

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/VolcanoBlock#79]
I might miss something but I can't seem to be able to get iesnium. 

I looked in the overworld, the nether, the other and the end, using the otherworld goggles and the divination rod. Orechid apparently doesn't generate it, neither does the ore laser. The miner foliot would, but that one needs a iesnium pick to summon in the first place.

**Comment by Draxial** [comment]
Currently the only way to get Iesnium is this: "Throwing a block of compressed netherrack into spirit fire gives the occultism variant of netherrack"
