### ISSUE TITLE
Missing fertilizer recipes for MA in Phytogenic Insolator

### ISSUE THREAD

**Issue by Tolana** [AllTheMods/VolcanoBlock#8]
Mystical Agriculture seeds do not have fertilizer recipes in the phytogenic Insolator. 

For example, inferium essence with phyto-gro fertilizer in the phytogenic insolator, does nothing (the fertilizer doesn't get used, and output is the same)

on 0.3

**Comment by Tolana** [comment]
It's an odd issue.
I've checked and compared with ATM8, where it works phyto-gro gives 3x essence with MA seeds.
And when you look up MA seeds in JEI you see the optional catalyst cycle in the JEI window for the recipe.

And the kubejs script "crops.js" is identical. 
I even unpacked thermal expansion mod jar, and looked at the catalyst phytogro .json file, which is also identical.
(says secondary mod should give 3x on both atm8 and vb 0.3)

So maybe somethings changed in 1.20 with thermal, and the way you have to register crops & their catalysts, or it's just broken for some reason.

**Comment by oly2o6** [comment]
Merged!
