### ISSUE TITLE
No Iron Furnaces?

### ISSUE THREAD

**Issue by Eidelmaim** [AllTheMods/VolcanoBlock#83]
i can see there is an iron furnace config file but there is no iron furnaces from the IronFurnace mod in the pack. intentional or not?

[Mods](https://prnt.sc/fkltFlf3nL9Y) - image
[Configs](https://prnt.sc/9xBpV2q199w4) - image

**Comment by Trontastic** [comment]
Removed due to lags

Suggestions are there tho:
https://github.com/AllTheMods/VolcanoBlock/issues/2

**Comment by Draxial** [comment]
As Trontastic said it was removed due to a big lag spike.
