### ISSUE TITLE
MA tier 5 seeds still showing a secondary output chance

### ISSUE THREAD

**Issue by joeychin01** [AllTheMods/VolcanoBlock#86]
On screen tooltip shows the following, despite secondary chances being disabled.
Diamond Seeds
Growth: Mature
Tier: 5
Secondary Chance: 20%

**Comment by Draxial** [comment]
Hmmm, could you give more details?
I just checked all farmlands and don't see any secondary change info:
in order: insanium, inferium, prudentium, tertium, imperium, supremium, 
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/4c2cb4e6-0baf-406e-ad8f-d6abdbca7661)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/343b2750-7a9a-4acb-930a-cab6977fff27)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/6d986abd-f155-4ce7-879c-e1398e3add14)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/9ba78e0d-bd75-4821-8e04-2849ff22f0c5)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/adfd132c-93db-49c0-aedd-9cd1d7b87ab2)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/c3e986b5-659b-4e56-b781-611e92b38a4c)
