### ISSUE TITLE
Generator Galore Version not working

### ISSUE THREAD

**Issue by ChrisHanes3** [AllTheMods/VolcanoBlock#88]
![image](https://github.com/AllTheMods/VolcanoBlock/assets/87105607/8c016a65-5d8a-4566-bb04-03303f2904df)

I am running a server using the v1.0.3 server pack and the v1.0.3 modpack but am getting this error message.  
I noticed that the version on curse forge shows up as 1.0.2 in the preview (see below)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/87105607/37c4c62e-d16c-4d47-8908-c90690ff6f01)

Verifying the pack version via curseforge 'change version' i get the following:
![image](https://github.com/AllTheMods/VolcanoBlock/assets/87105607/45d08462-8e67-4e84-afa2-26234c0fb194)

I've also tried copying and pasting the most up to date file (the one from the client modpack) to the server with no luck

**Comment by Draxial** [comment]
I'd suggest reinstalling the entire modpack in the server, sometimes for some reason a weird corruption happens
just back-up your server.properties and world folder and try again

**Comment by ChrisHanes3** [comment]
Yep, that worked.  Idk what happened but thank you :)
