### ISSUE TITLE
jei config

### ISSUE THREAD

**Issue by infinityblade21** [AllTheMods/VolcanoBlock#89]
hey dont wanna sound rude or anything in any way but could you when it gets updated not include the jei config or atleast the client config for it so that it doesnt get reset like i get that its not that hard to redo the config but yeah, thanks for reading btw again sorry if that sounded rude at all

**Comment by Draxial** [comment]
No worries, you weren't rude at all!
You mean the config/jei/jei-client.ini ?

**Comment by infinityblade21** [comment]
sorry thought i replied to this yeah i meant that my bad abt that

**Comment by billbertking1** [comment]
Forge needs updated for configured mod to work properly to edit in game at the least; unsure why it's not saving upon updating
