### ISSUE TITLE
Iron Jetpacks Missing after update

### ISSUE THREAD

**Issue by GhostCornfed** [AllTheMods/VolcanoBlock#90]
I had an Emerald Jetpack from Iron Jetpacks and now it is and "Undefined Jetpack". The coils used for making them are still in the game, however the jetpacks are not. This change was not included in the patch notes. Please advise.

**Comment by Draxial** [comment]
Something weird going with curse; delete these and you should be good to go: 
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/5450834d-4544-4927-b9fc-dfc04bdf543d)
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/44d352b9-b659-4047-af60-7d372ef8c94a)
