### ISSUE TITLE
Early game ore doubling with Create Mixer/Basin and Ore Hammer uses hammer

### ISSUE THREAD

**Issue by FidgetStick** [AllTheMods/VolcanoBlock#92]
Ore doubling using the Ore Hammer and Create Mixer processes the recipe once and uses the hammer.

**Comment by pillsbutch** [comment]
whats the issue ore hammer is supposed to make the dust witch allows for ore doubling early on thats intended

**Comment by Trontastic** [comment]
Create has a bug it delete the hammer after a single use
Next Create version fix this but there will be no more infinite hammering with the mixer.

You should use Macerator from IC2 to double ores
