### ISSUE TITLE
mod change or maybe add more in the modpack

### ISSUE THREAD

**Issue by zResck** [AllTheMods/VolcanoBlock#93]
> `I missed the better backpack mod than is currently the useful backpack, I don't think it's that useful this mod doesn't have much to do with it`

> Suggestion
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
https://www.curseforge.com/minecraft/mc-mods/sophisticated-core
https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

> Extras

it has much more functions than the current mod that is in the modpack and in my opinion it is one of the best backpack mods currently and it would be great to be in the modpack

**Comment by Trontastic** [comment]
I think its intentional that we got these chest and backpack mods.
Sophisticated makes it too easy and make some mods useless.
But can be wrong about the vision.

**Comment by zResck** [comment]
I really miss her, both parts make it easier but also help a lot

**Comment by Mitchell5200** [comment]
#2  for mod suggestions, not new issues
