### ISSUE TITLE
crahing when i try to start it

### ISSUE THREAD

**Issue by dale4234** [AllTheMods/VolcanoBlock#95]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9241c2b60, pid=5732, tid=3648
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x192b60]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\Users\Dale\Documents\curseforge\minecraft\Install\bin\eb0bfae569f53973d65e82076f45a44092ad6180 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.7.12 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-43.2.14.jar,forge-43.2.14 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries --module-path=C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.3/asm-9.3.jar;C:\Users\Dale\Documents\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx24800m -Xms256m -Dminecraft.applet.TargetDirectory=C:\Users\Dale\Documents\curseforge\minecraft\Instances\All the Mods Volcano Block ATMVB -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\Users\Dale\Documents\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username the_mted2 --version forge-43.2.14 --gameDir C:\Users\Dale\Documents\curseforge\minecraft\Instances\All the Mods Volcano Block ATMVB --assetsDir C:\Users\Dale\Documents\curseforge\minecraft\Install\assets --assetIndex 1.19 --uuid f7528f10a3624f718f5164a832801e3f -o --clientId YTkwNDVjYWMtMzFmZi00NWU0LWEyMjEtMzkwNmExMmQyMDMz --xuid 2535452708984897 --userType msa --versionType release --width 1920 --height 1080 --launchTarget forgeclient --fml.forgeVersion 43.2.14 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Host: AMD Ryzen 5 3600 6-Core Processor              , 12 cores, 31G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2364)
Time: Tue Aug 22 20:17:39 2023 GMT Summer Time elapsed time: 18.777747 seconds (0d 0h 0m 18s)

---------------  S Y S T E M  ---------------

OS:
 Windows 10 , 64 bit Build 19041 (10.0.19041.2364)
OS uptime: 4 days 0:24 hours

CPU: total 12 (initial active 12) (12 cores per cpu, 2 threads per core) family 23 model 113 stepping 0 microcode 0x0, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4a, sse4.1, sse4.2, popcnt, lzcnt, tsc, tscinvbit, avx, avx2, aes, clmul, bmi1, bmi2, adx, sha, fma, vzeroupper, clflush, clflushopt

Memory: 4k page, system-wide physical 32699M (20790M free)
TotalPageFile size 39867M (AvailPageFile size 22888M)
current process WorkingSet (physical memory assigned to process): 1897M, peak: 1897M
current process commit charge ("private bytes"): 1985M, peak: 2072M

vm_info: OpenJDK 64-Bit Server VM (17.0.3+7-LTS) for windows-amd64 JRE (17.0.3+7-LTS), built on Apr 20 2022 04:24:16 by "" with MS VC++ 16.10 / 16.11 (VS2019)

END.

**Comment by Mitchell5200** [comment]
AMD GPU driver crash, below copied from discord

The `atio6axx` "Problematic frame" in a `hs_err_pid` file, is part of the **AMD** driver for the GPU, there's a bad version of the AMD drivers that instantly crashes on an OpenGL task, 
Reinstall/Fresh install your drivers from https://www.amd.com/en/support

**IF** you do not have an **AMD GPU**, then you need to set your system to be using that GPU instead of the AMD integrated GPU on the CPU

**Comment by Draxial** [comment]
If you still have any issues with this, please reopen the issue, thank you!
