### ISSUE TITLE
Weird Duplication/Deletion/Swap/¯\_(ツ)_/¯ Bug

### ISSUE THREAD

**Issue by Karma-Fox** [AllTheMods/VolcanoBlock#97]
I am not sure what happened but I was using a copper ore hammer from AllTheOres to make iron plates inside of the Ars Nouveau Storage Lectern. About 10-20 pieces in (clicking really fast), the hammer just started to duplicate and I didn't really notice what was going on (just thought the small 55 in the bottom right of the hammer was weird). I then noticed I have over 200 copies of the hammer in my colossal chest and trying to use them doesn't actually work (one worked and went to -45 durability, but the rest just didn't ). When I tried to get rid of them, all of the items in my inventory turned into them (anything not on the hot bar). Even my time in a bottle vanished. 

We thought FTB Backups 2 was part of the mod pack (got confused with Mystical Block) so we thought we were automatically keeping 30-minute backups, but we weren't (we are now though). So, whatever I lost is forever gone.

This is on the current version of the mod pack, 1.0.4, and on a dedicated server. Also, we've gone through the logs with a fine-toothed comb and there is nothing recorded in them. From hours before to the time we shut down the server to add FTB Backups 2, the only thing recorded in them is dimensional tick rates.

**Comment by Draxial** [comment]
Might be related to this bug on their side:
https://github.com/baileyholl/Ars-Nouveau/issues/1016
