### ISSUE TITLE
Main Quest Flux Sieve No longer registering in latest patch

### ISSUE THREAD

**Issue by DelusionalWizard** [AllTheMods/VolcanoBlock#98]

**Comment by Draxial** [comment]
Make sure you complete the 4 previous quests:
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/8793ad3e-9461-4b2d-97ca-20e054f300ab)

I just tested manually(created a new instance, manually gave the items to me while on survival, from the top all the way to the bottom) and it's working on 1.0.4 for me:
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/17d384fa-efed-4341-bb2a-3f3b6c7e2ace)

if still not working, can you please send us a screenshot of your questbook like the one I sent, and one from inside the quest?
also the items you crafted too with their tags, like:
![image](https://github.com/AllTheMods/VolcanoBlock/assets/53184989/60f1e171-3e3f-497d-8e45-d4f564c9c8af)
(press F3 + h to show advanced tooltips)
